### ISSUE TITLE
Code Quality: isSet could be simplified

### ISSUE THREAD

**Issue by itsallvoodoo** [itsallvoodoo/OWASP-Stinger#8]
Change rules/Ruleset.java:588 to !isSet to simplify code.

**Comment by AUmrysh** [comment]
This was fixed in https://github.com/itsallvoodoo/OWASP-Stinger/commit/0579bd472280b8afdca25f8b486381e2a0751982

**Comment by itsallvoodoo** [comment]
Good observation, must have fixed it in another branch. Will close.
